### ISSUE TITLE
ROS noetic release

### ISSUE THREAD

**Issue by rickstaa** [davetcoleman/moveit_sim_controller#8]
Since the `noetic-branch` of the [ros_control_boilerplate](https://github.com/PickNikRobotics/ros_control_boilerplate/pull/46) has been released I think we can also release the Noetic version of the `moveit_sim_Controller`:

#### TODOS

- [x] Create the `noetic-devel` branch.
- [x] Merge https://github.com/PickNikRobotics/moveit_sim_controller/pull/9 onto the `noetic-devel` branch.
- [x] Perform tests.
- [x] Release the debian.

**Comment by JafarAbdi** [comment]
Done https://github.com/ros/rosdistro/pull/31059

**Comment by rickstaa** [comment]
@JafarAbdi Wow that's fast! Thanks a lot.
